version: "3.9"

services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    expose:
      - "6379"

  celery_worker:
    build: .
    command: celery -A hw30 worker --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    command: celery -A hw30 beat --loglevel=info
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  static_volume:
  redis_data: